Added initial NRK-sync support
trakt-tools/universal-trakt-scrobbler pull request #1
Opened 2020-02-18 13:54 UTC by MrMamen

2020-02-20 12:13 UTC, rafaelgomesxyz requested changes

2020-02-20 12:13 UTC, rafaelgssa commented on src/modules/history/streaming-services/nrk/NrkApi.js
> +          .then(this.loadTraktHistory.bind(this));
Same thing with the binding.

2020-02-20 12:13 UTC, rafaelgssa commented on src/modules/history/streaming-services/nrk/NrkApi.js
> +      promises = items.map(this.loadTraktItemHistory.bind(this));
Binding here too.

2020-02-20 12:13 UTC, rafaelgssa commented on src/modules/history/streaming-services/nrk/NrkPage.js
> +import { NetflixStore } from '../netflix/NetflixStore';
Same issue with the NetflixStore.

2020-02-26 16:33 UTC, rafaelgomesxyz approved these changes

2020-02-26 16:33 UTC, merged