Telia play history sync
trakt-tools/universal-trakt-scrobbler pull request #52
Opened 2020-11-07 17:55 UTC by schteff

A sync that fetches the watched info of as many episodes and movies as possible using the "Continue watching" list and "My list" features in Telia Play.

2020-11-12 22:25 UTC, MrMamen commented on src/streaming-services/telia-play/telia-play.ts
> +			const watchedEps = allEpisodes.filter((ep) => this.pctWatched(wMap.get(ep.loopId)) > 10);
clever!

2020-11-12 22:27 UTC, MrMamen requested changes
Remember to update the readme file with support for teliaplay. You could also make a note somewhere that this only works with the Swedish version at this time.

2020-11-12 22:27 UTC, MrMamen commented on src/streaming-services/telia-play/telia-play.ts
> +		// console.log(url, JSON.parse(response));
Remove this, I guess.

2020-11-16 21:12 UTC, schteff commented
Telia Play seems to only have a Swedish version. Even if I change language to English in the settings the website (https://www.teliaplay.se/) is in Swedish. I think the setting only changes the preferred audio language to English. 

So I just added a line to the list of supported streaming services in the readme.

2020-11-19 22:02 UTC, MrMamen submitted a review, later dismissed
Sorry for the delay. See if you can find the error with matching movies on or around TraktSearch.ts line 152. Or you could just leave it as it is and file a bug while merging this.

2020-11-19 23:06 UTC, schteff commented
Yeah, I added a fix for the mismatched movies. If only one search result is found, it is selected ignoring the title and year matching. 

I still experience many other weird "Not found" mismatches the first time I run the sync. But if I close the tab and run it again these disappear. If I manage to reproduce this I will file a bug or fix it later. 

I guess you can merge this pull request now :)

2020-11-20 12:31 UTC, MrMamen approved these changes

2020-11-24 12:56 UTC, merged

2020-11-24 20:46 UTC, MrMamen commented
> Telia Play seems to only have a Swedish version. Even if I change language to English in the settings the website (https://www.teliaplay.se/) is in Swedish. I think the setting only changes the preferred audio language to English.
> 
> So I just added a line to the list of supported streaming services in the readme.

I found at least this:
https://www.teliaplay.lt
Seems like a localized clone to me.

2020-11-24 21:39 UTC, schteff commented
Yeah, I can't sign in there with my account though. But I guess my sync code should work there to if the .it domains are added to the whitelist.

2020-11-24 21:43 UTC, MrMamen commented
I did something similar with viaplay. You don't need to do anything with it however. Can wait until someone requests it.